vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
        imgicons:
            uri_prefix: /assets/img/user
            upload_destination: '%kernel.project_dir%/public/assets/img/user'
        products:
            uri_prefix: /assets/img/user
            upload_destination: '%kernel.project_dir%/public/assets/img/product'
    
